#! /bin/bash

if [ -f ~/.bashrc ]; then
  rm ~/.bashrc
fi
ln -s ~/dotfiles/.bashrc ~/.bashrc

if [ -f ~/.bash_aliases ]; then
  rm ~/.bash_aliases 
fi
ln -s ~/dotfiles/.bash_aliases ~/.bash_aliases

if [ -f ~/.bash_perso ]; then
  rm ~/.bash_perso
fi
ln -s ~/dotfiles/.bash_perso ~/.bash_perso

if [ -f ~/.vimrc ]; then
  rm ~/.vimrc
fi
ln -s ~/dotfiles/.vimrc ~/.vimrc


source ~/.bashrc

